import React, { useState } from 'react';
import { Sparkles, CheckCircle2, Lightbulb, ArrowRight, Check } from 'lucide-react';

/**
 * Recommendations Panel Component
 * Displays Next-Best Action cards generated by Recommendation Agent.
 * Features Priority Badges, Reason text, and interactive Action Buttons.
 */
export default function RecommendationsPanel({ recommendations = [] }) {
  const [executedItems, setExecutedItems] = useState({});

  const defaultRecs = [
    {
      title: 'Explain Zero Interest EMI',
      priority: 'High',
      reason: 'Customer requested Pay-in-3 installment terms and interest conditions.'
    },
    {
      title: 'Offer Application Link',
      priority: 'Medium',
      reason: 'Customer is eligible; offer instant digital checkout link.'
    }
  ];

  const items = recommendations.length > 0 ? recommendations : defaultRecs;

  const handleExecute = (index) => {
    setExecutedItems((prev) => ({ ...prev, [index]: true }));
  };

  const getPriorityStyle = (priority) => {
    switch (priority?.toLowerCase()) {
      case 'high':
        return 'bg-red-500/10 text-red-400 border-red-500/30';
      case 'medium':
        return 'bg-sky-500/10 text-sky-400 border-sky-500/30';
      default:
        return 'bg-slate-800 text-slate-400 border-slate-700';
    }
  };

  return (
    <div className="bg-slate-900/90 border border-slate-800 rounded-xl p-5 shadow-xl backdrop-blur-md space-y-4">
      {/* Panel Header */}
      <div className="flex items-center justify-between pb-3 border-b border-slate-800">
        <div className="flex items-center space-x-2">
          <div className="p-1.5 bg-sky-500/10 rounded-lg text-sky-400 border border-sky-500/20">
            <Sparkles className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-slate-100">AI Suggestions</h3>
            <p className="text-[11px] text-slate-400">Recommendation Agent Engine</p>
          </div>
        </div>
        <span className="text-[10px] font-mono font-semibold bg-sky-500/10 text-sky-400 border border-sky-500/20 px-2 py-0.5 rounded-full">
          {items.length} Actions Available
        </span>
      </div>

      {/* Action Cards List */}
      <div className="space-y-3">
        {items.map((rec, index) => {
          const isDone = executedItems[index];
          return (
            <div
              key={index}
              className={`p-3.5 bg-slate-950/70 border rounded-xl transition-all space-y-2.5 group ${
                isDone ? 'border-emerald-500/40 bg-emerald-950/20' : 'border-slate-800 hover:border-sky-500/40'
              }`}
            >
              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-2">
                  <CheckCircle2 className={`w-4 h-4 shrink-0 ${isDone ? 'text-emerald-400' : 'text-sky-400'}`} />
                  <span className="font-semibold text-xs text-slate-100 group-hover:text-sky-300 transition-colors">
                    {rec.title}
                  </span>
                </div>
                <span className={`text-[9px] font-extrabold uppercase px-2 py-0.5 rounded-full border ${getPriorityStyle(rec.priority)}`}>
                  {rec.priority} Priority
                </span>
              </div>

              <div className="pl-6 pt-1 border-t border-slate-800/50 flex items-start space-x-1.5 text-[11px]">
                <Lightbulb className="w-3.5 h-3.5 text-amber-400 shrink-0 mt-0.5" />
                <div className="flex-1">
                  <span className="font-semibold text-slate-400">Reason: </span>
                  <span className="text-slate-300">{rec.reason}</span>
                </div>
              </div>

              {/* Action Execute Button */}
              <div className="pt-1.5 flex justify-end">
                <button
                  onClick={() => handleExecute(index)}
                  disabled={isDone}
                  className={`flex items-center space-x-1 px-3 py-1.5 rounded-lg text-xs font-extrabold transition-all cursor-pointer ${
                    isDone
                      ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/30'
                      : 'bg-sky-500 hover:bg-sky-400 text-slate-950 shadow-md shadow-sky-500/20'
                  }`}
                >
                  {isDone ? (
                    <>
                      <Check className="w-3.5 h-3.5" />
                      <span>Action Executed</span>
                    </>
                  ) : (
                    <>
                      <span>Execute Action</span>
                      <ArrowRight className="w-3.5 h-3.5" />
                    </>
                  )}
                </button>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
